import { JobDto } from './dto/job.dto.js';

export const sampleJobs: Omit<JobDto, 'recruiterId'>[] = [
  {
    id: '1',
    companyName: 'TechNova',
    companyLogo: null,
    companyWebsite: 'https://technova.io',
    title: 'Frontend Developer',
    jobType: 'Full-time',
    description:
      'Develop responsive React applications and collaborate with UX designers.',
    qualifications: ['React', 'TypeScript', 'CSS', 'REST APIs'],
    benefits: ['Remote work', 'Health insurance'],
    responsibilities: ['Build UI components', 'Optimize performance'],
    location: 'Berlin',
    country: 'Germany',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 55000,
    salaryMax: 75000,
    applicationLink: 'https://technova.io/careers/1',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '2',
    companyName: 'CloudSync',
    companyLogo: null,
    companyWebsite: 'https://cloudsync.com',
    title: 'Backend Engineer (Node.js)',
    jobType: 'Full-time',
    description:
      'Design and maintain REST APIs and microservices in Node.js and Express.',
    qualifications: ['Node.js', 'Express', 'MongoDB'],
    benefits: ['401k', 'Stock options'],
    responsibilities: ['Develop APIs', 'Maintain databases'],
    location: 'San Francisco',
    country: 'USA',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 90000,
    salaryMax: 120000,
    applicationLink: 'https://cloudsync.com/careers/2',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '3',
    companyName: 'DataForge',
    companyLogo: null,
    companyWebsite: 'https://dataforge.ai',
    title: 'Data Scientist',
    jobType: 'Full-time',
    description:
      'Analyze data and build machine learning models for business insights.',
    qualifications: ['Python', 'TensorFlow', 'Data Analysis', 'SQL'],
    benefits: ['Gym membership', 'Flexible hours'],
    responsibilities: [
      'Build ML models',
      'Clean datasets',
      'Collaborate with data engineers',
    ],
    location: 'London',
    country: 'UK',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 70000,
    salaryMax: 95000,
    applicationLink: 'https://dataforge.ai/jobs/3',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '4',
    companyName: 'BuildIt',
    companyLogo: null,
    companyWebsite: 'https://buildit.dev',
    title: 'Full Stack Developer',
    jobType: 'Contract',
    description:
      'Work on both frontend and backend for web-based construction tools.',
    qualifications: ['React', 'Node.js', 'PostgreSQL', 'Docker'],
    benefits: ['Flexible contract'],
    responsibilities: ['Integrate APIs', 'Develop UI'],
    location: 'Remote',
    country: 'Global',
    hourlyRate: 45,
    fixedBudget: null,
    salaryMin: null,
    salaryMax: null,
    applicationLink: 'https://buildit.dev/jobs/4',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '5',
    companyName: 'ByteLogic',
    companyLogo: null,
    companyWebsite: 'https://bytelogic.io',
    title: 'Software Engineer (Java)',
    jobType: 'Full-time',
    description: 'Develop enterprise-level software in Java and Spring Boot.',
    qualifications: ['Java', 'Spring Boot', 'MySQL'],
    benefits: ['Annual bonus', 'Paid leave'],
    responsibilities: ['Write backend logic', 'Optimize services'],
    location: 'Amsterdam',
    country: 'Netherlands',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 65000,
    salaryMax: 90000,
    applicationLink: 'https://bytelogic.io/careers/5',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '6',
    companyName: 'GreenTech',
    companyLogo: null,
    companyWebsite: 'https://greentech.org',
    title: 'Frontend Engineer (Vue.js)',
    jobType: 'Part-time',
    description:
      'Implement user interfaces using Vue 3 for sustainability applications.',
    qualifications: ['Vue.js', 'HTML', 'CSS', 'REST APIs'],
    benefits: ['Remote', 'Eco-friendly team'],
    responsibilities: ['Build UI', 'Integrate API data'],
    location: 'Remote',
    country: 'Global',
    hourlyRate: 35,
    fixedBudget: null,
    salaryMin: null,
    salaryMax: null,
    applicationLink: 'https://greentech.org/jobs/6',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '7',
    companyName: 'CyberCore',
    companyLogo: null,
    companyWebsite: 'https://cybercore.io',
    title: 'Cybersecurity Analyst',
    jobType: 'Full-time',
    description: 'Monitor and protect systems from cybersecurity threats.',
    qualifications: ['Network Security', 'Python', 'Incident Response'],
    benefits: ['Remote work', 'Training budget'],
    responsibilities: ['Perform audits', 'Respond to incidents'],
    location: 'Toronto',
    country: 'Canada',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 80000,
    salaryMax: 100000,
    applicationLink: 'https://cybercore.io/jobs/7',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '8',
    companyName: 'AIWorks',
    companyLogo: null,
    companyWebsite: 'https://aiworks.ai',
    title: 'Machine Learning Engineer',
    jobType: 'Full-time',
    description:
      'Design, train, and deploy ML models for computer vision systems.',
    qualifications: ['Python', 'PyTorch', 'Deep Learning', 'TensorFlow'],
    benefits: ['Stock options', 'Hybrid work'],
    responsibilities: ['Model development', 'Model optimization'],
    location: 'Boston',
    country: 'USA',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 95000,
    salaryMax: 130000,
    applicationLink: 'https://aiworks.ai/jobs/8',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '9',
    companyName: 'Webify',
    companyLogo: null,
    companyWebsite: 'https://webify.dev',
    title: 'UI/UX Designer',
    jobType: 'Full-time',
    description: 'Create modern web and mobile interface designs.',
    qualifications: ['Figma', 'UX Research', 'Prototyping'],
    benefits: ['Health plan', 'Paid vacation'],
    responsibilities: ['Design UI screens', 'Conduct user testing'],
    location: 'Paris',
    country: 'France',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 55000,
    salaryMax: 75000,
    applicationLink: 'https://webify.dev/jobs/9',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '10',
    companyName: 'SmartTrade',
    companyLogo: null,
    companyWebsite: 'https://smarttrade.com',
    title: 'DevOps Engineer',
    jobType: 'Full-time',
    description: 'Automate CI/CD pipelines and manage cloud infrastructure.',
    qualifications: ['AWS', 'Docker', 'Kubernetes', 'Terraform'],
    benefits: ['Remote work', 'Bonuses'],
    responsibilities: ['Deploy microservices', 'Maintain CI/CD'],
    location: 'Sydney',
    country: 'Australia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 90000,
    salaryMax: 120000,
    applicationLink: 'https://smarttrade.com/jobs/10',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '11',
    companyName: 'CodeVerse',
    companyLogo: null,
    companyWebsite: 'https://codeverse.dev',
    title: 'Frontend Developer (Next.js)',
    jobType: 'Full-time',
    description:
      'Work with Next.js and Tailwind CSS to build modern web experiences.',
    qualifications: ['Next.js', 'React', 'Tailwind CSS'],
    benefits: ['Remote', 'Flexible schedule'],
    responsibilities: ['Build pages', 'Collaborate with backend team'],
    location: 'Remote',
    country: 'Global',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 60000,
    salaryMax: 85000,
    applicationLink: 'https://codeverse.dev/jobs/11',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '12',
    companyName: 'FinEdge',
    companyLogo: null,
    companyWebsite: 'https://finedge.finance',
    title: 'Backend Developer (Python)',
    jobType: 'Full-time',
    description: 'Develop secure and scalable APIs for financial platforms.',
    qualifications: ['Python', 'Django', 'REST', 'PostgreSQL'],
    benefits: ['Bonus', 'Hybrid work'],
    responsibilities: ['API development', 'Database optimization'],
    location: 'New York',
    country: 'USA',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 95000,
    salaryMax: 115000,
    applicationLink: 'https://finedge.finance/jobs/12',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '13',
    companyName: 'EduSmart',
    companyLogo: null,
    companyWebsite: 'https://edusmart.io',
    title: 'React Developer (EdTech)',
    jobType: 'Contract',
    description: 'Build education web apps with React and Firebase.',
    qualifications: ['React', 'Firebase', 'TypeScript'],
    benefits: ['Contract-based', 'Remote'],
    responsibilities: ['Develop UI', 'Integrate backend'],
    location: 'Remote',
    country: 'Global',
    hourlyRate: 40,
    fixedBudget: null,
    salaryMin: null,
    salaryMax: null,
    applicationLink: 'https://edusmart.io/jobs/13',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '14',
    companyName: 'DesignPro',
    companyLogo: null,
    companyWebsite: 'https://designpro.com',
    title: 'Graphic Designer',
    jobType: 'Full-time',
    description: 'Create visuals for marketing campaigns and brand identity.',
    qualifications: ['Photoshop', 'Illustrator', 'Branding'],
    benefits: ['Paid holidays', 'Training allowance'],
    responsibilities: ['Create visuals', 'Collaborate with marketing team'],
    location: 'Lisbon',
    country: 'Portugal',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 40000,
    salaryMax: 60000,
    applicationLink: 'https://designpro.com/jobs/14',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '15',
    companyName: 'AutoAI',
    companyLogo: null,
    companyWebsite: 'https://autoai.tech',
    title: 'AI Research Engineer',
    jobType: 'Full-time',
    description:
      'Research and implement novel AI models for self-driving systems.',
    qualifications: ['Python', 'Deep Learning', 'Computer Vision'],
    benefits: ['Stock options', 'Free lunch'],
    responsibilities: ['Develop algorithms', 'Test models'],
    location: 'San Jose',
    country: 'USA',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 120000,
    salaryMax: 150000,
    applicationLink: 'https://autoai.tech/jobs/15',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '16',
    companyName: 'CodeLab',
    companyLogo: null,
    companyWebsite: 'https://codelab.dev',
    title: 'Frontend Intern',
    jobType: 'Internship',
    description: 'Assist in developing web UI using React and Tailwind CSS.',
    qualifications: ['React', 'HTML', 'CSS'],
    benefits: ['Internship certificate'],
    responsibilities: ['Assist developers', 'Fix UI bugs'],
    location: 'Remote',
    country: 'Global',
    hourlyRate: 10,
    fixedBudget: null,
    salaryMin: null,
    salaryMax: null,
    applicationLink: 'https://codelab.dev/internships/16',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '17',
    companyName: 'NextEra',
    companyLogo: null,
    companyWebsite: 'https://nextera.io',
    title: 'Next.js Engineer',
    jobType: 'Full-time',
    description:
      'Work on high-performance web applications with Next.js and TypeScript.',
    qualifications: ['Next.js', 'TypeScript', 'React'],
    benefits: ['Remote', 'Flexible hours'],
    responsibilities: ['Develop SSR pages', 'Improve SEO performance'],
    location: 'Remote',
    country: 'Global',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 65000,
    salaryMax: 90000,
    applicationLink: 'https://nextera.io/jobs/17',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '18',
    companyName: 'HealthLink',
    companyLogo: null,
    companyWebsite: 'https://healthlink.org',
    title: 'Backend Engineer (Go)',
    jobType: 'Full-time',
    description: 'Develop healthcare microservices using Go and PostgreSQL.',
    qualifications: ['Go', 'Microservices', 'PostgreSQL'],
    benefits: ['Health insurance', 'Hybrid work'],
    responsibilities: ['Build APIs', 'Manage databases'],
    location: 'Chicago',
    country: 'USA',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 95000,
    salaryMax: 115000,
    applicationLink: 'https://healthlink.org/jobs/18',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '19',
    companyName: 'PayFlex',
    companyLogo: null,
    companyWebsite: 'https://payflex.com',
    title: 'Frontend Developer (Angular)',
    jobType: 'Full-time',
    description: 'Work on fintech dashboards using Angular and TypeScript.',
    qualifications: ['Angular', 'TypeScript', 'SCSS'],
    benefits: ['Remote', 'Annual bonus'],
    responsibilities: ['Develop UI', 'Fix UI bugs'],
    location: 'Madrid',
    country: 'Spain',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 60000,
    salaryMax: 80000,
    applicationLink: 'https://payflex.com/jobs/19',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '20',
    companyName: 'AgriData',
    companyLogo: null,
    companyWebsite: 'https://agridata.tech',
    title: 'Data Engineer',
    jobType: 'Full-time',
    description:
      'Design and maintain ETL pipelines for agricultural analytics.',
    qualifications: ['Python', 'Airflow', 'ETL', 'AWS'],
    benefits: ['Hybrid work', 'Bonus'],
    responsibilities: ['Manage data pipelines', 'Optimize queries'],
    location: 'Nairobi',
    country: 'Kenya',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 75000,
    salaryMax: 95000,
    applicationLink: 'https://agridata.tech/jobs/20',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },

  // ----------------- ACCOUNTING JOBS (20) -----------------
  {
    id: '1',
    companyName: 'FinEdge Consulting',
    companyLogo: null,
    companyWebsite: 'https://finedge.com',
    title: 'Junior Accountant',
    jobType: 'Full-time',
    description:
      'Assist with daily bookkeeping, financial record management, and reconciliation.',
    qualifications: ["Bachelor's Degree in Accounting", 'Excel', 'QuickBooks'],
    benefits: ['Health Insurance', 'Paid Leave'],
    responsibilities: [
      'Prepare journal entries',
      'Reconcile accounts',
      'Assist audits',
    ],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 600,
    salaryMax: 800,
    applicationLink: 'https://finedge.com/jobs/1',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '2',
    companyName: 'Green Finance PLC',
    companyLogo: null,
    companyWebsite: 'https://greenfinance.com',
    title: 'Senior Accountant',
    jobType: 'Full-time',
    description:
      'Manage monthly closings and financial reporting for internal and external stakeholders.',
    qualifications: ['CPA Certification', '5+ years of accounting experience'],
    benefits: ['Remote work', 'Annual bonus'],
    responsibilities: [
      'Prepare reports',
      'Ensure GAAP compliance',
      'Lead audit activities',
    ],
    location: 'Remote',
    country: 'Global',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1200,
    salaryMax: 1600,
    applicationLink: 'https://greenfinance.com/jobs/2',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '3',
    companyName: 'BlueSky Manufacturing',
    companyLogo: null,
    companyWebsite: 'https://bluesky.com',
    title: 'Cost Accountant',
    jobType: 'On-site',
    description:
      'Analyze production costs and prepare cost reports for management decisions.',
    qualifications: ['Bachelor’s in Accounting', 'Cost analysis experience'],
    benefits: ['Meal Allowance'],
    responsibilities: ['Track cost centers', 'Support budget planning'],
    location: 'Nairobi',
    country: 'Kenya',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 900,
    salaryMax: 1200,
    applicationLink: 'https://bluesky.com/jobs/3',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '4',
    companyName: 'Zenith Auditors',
    companyLogo: null,
    companyWebsite: 'https://zenithaudit.com',
    title: 'Audit Associate',
    jobType: 'Full-time',
    description: 'Conduct financial audits for small and medium enterprises.',
    qualifications: [
      'Bachelor’s in Accounting or Finance',
      'Strong attention to detail',
    ],
    benefits: ['Career growth', 'Training programs'],
    responsibilities: ['Perform audits', 'Prepare audit reports'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 800,
    salaryMax: 1000,
    applicationLink: 'https://zenithaudit.com/jobs/4',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '5',
    companyName: 'EcoTrade Ltd',
    companyLogo: null,
    companyWebsite: 'https://ecotrade.com',
    title: 'Accounts Payable Specialist',
    jobType: 'Contract',
    description: 'Manage invoices, payments, and vendor relationships.',
    qualifications: ['Diploma or higher in Accounting', '2 years experience'],
    benefits: ['Flexible hours'],
    responsibilities: ['Review invoices', 'Process payments'],
    location: 'Kigali',
    country: 'Rwanda',
    hourlyRate: 20,
    fixedBudget: null,
    salaryMin: null,
    salaryMax: null,
    applicationLink: 'https://ecotrade.com/jobs/5',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '6',
    companyName: 'Summit Partners',
    companyLogo: null,
    companyWebsite: 'https://summitpartners.com',
    title: 'Tax Accountant',
    jobType: 'Full-time',
    description: 'Prepare tax filings and advise clients on compliance.',
    qualifications: ['CPA license', 'Tax law knowledge'],
    benefits: ['Bonus', 'Hybrid work'],
    responsibilities: ['File tax returns', 'Support audits'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1100,
    salaryMax: 1400,
    applicationLink: 'https://summitpartners.com/jobs/6',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '7',
    companyName: 'BrightBooks',
    companyLogo: null,
    companyWebsite: 'https://brightbooks.io',
    title: 'Bookkeeper',
    jobType: 'Part-time',
    description: 'Maintain accurate books for multiple small businesses.',
    qualifications: ['Experience with Xero or QuickBooks'],
    benefits: ['Remote'],
    responsibilities: ['Record transactions', 'Generate reports'],
    location: 'Remote',
    country: 'Global',
    hourlyRate: 18,
    fixedBudget: null,
    salaryMin: null,
    salaryMax: null,
    applicationLink: 'https://brightbooks.io/jobs/7',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '8',
    companyName: 'Prime Holdings',
    companyLogo: null,
    companyWebsite: 'https://primeholdings.com',
    title: 'Accounts Receivable Officer',
    jobType: 'Full-time',
    description: 'Handle billing, collection, and reconciliation processes.',
    qualifications: ['Bachelor’s in Finance', 'Excel'],
    benefits: ['Paid leave', 'Healthcare'],
    responsibilities: ['Manage receivables', 'Prepare aging reports'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 850,
    salaryMax: 1100,
    applicationLink: 'https://primeholdings.com/jobs/8',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '9',
    companyName: 'FinServe Microfinance',
    companyLogo: null,
    companyWebsite: 'https://finserve.org',
    title: 'Financial Analyst',
    jobType: 'Full-time',
    description: 'Analyze financial statements and prepare projections.',
    qualifications: ["Bachelor's in Accounting or Economics"],
    benefits: ['Performance bonus'],
    responsibilities: ['Prepare budgets', 'Analyze variance'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1000,
    salaryMax: 1300,
    applicationLink: 'https://finserve.org/jobs/9',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '10',
    companyName: 'AgriTrade Co.',
    companyLogo: null,
    companyWebsite: 'https://agritrade.com',
    title: 'Payroll Accountant',
    jobType: 'Full-time',
    description:
      'Handle payroll accounting and employee benefits reconciliation.',
    qualifications: ['Accounting degree', 'Payroll system experience'],
    benefits: ['Medical coverage'],
    responsibilities: ['Process payroll', 'Maintain employee records'],
    location: 'Mekelle',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 900,
    salaryMax: 1100,
    applicationLink: 'https://agritrade.com/jobs/10',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '11',
    companyName: 'FinancePro Group',
    companyLogo: null,
    companyWebsite: 'https://financepro.com',
    title: 'Corporate Accountant',
    jobType: 'Full-time',
    description:
      'Assist with corporate consolidations and intercompany reconciliations.',
    qualifications: ['Bachelor’s in Accounting', 'ERP knowledge'],
    benefits: ['Health insurance'],
    responsibilities: ['Maintain general ledger', 'Assist with closing'],
    location: 'Lagos',
    country: 'Nigeria',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1200,
    salaryMax: 1500,
    applicationLink: 'https://financepro.com/jobs/11',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '12',
    companyName: 'AuditEase',
    companyLogo: null,
    companyWebsite: 'https://auditease.com',
    title: 'Forensic Accountant',
    jobType: 'Contract',
    description: 'Investigate financial discrepancies and fraud detection.',
    qualifications: ['CPA', 'Investigative skills'],
    benefits: ['Flexible work'],
    responsibilities: ['Analyze data', 'Prepare reports'],
    location: 'Remote',
    country: 'Global',
    hourlyRate: 45,
    fixedBudget: null,
    salaryMin: null,
    salaryMax: null,
    applicationLink: 'https://auditease.com/jobs/12',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '13',
    companyName: 'ClearLedger',
    companyLogo: null,
    companyWebsite: 'https://clearledger.org',
    title: 'Budget Officer',
    jobType: 'Full-time',
    description: 'Prepare organizational budgets and monitor spending.',
    qualifications: ['Finance or Accounting background'],
    benefits: ['Annual bonus'],
    responsibilities: ['Prepare reports', 'Advise departments'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 900,
    salaryMax: 1200,
    applicationLink: 'https://clearledger.org/jobs/13',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '14',
    companyName: 'BizCore Solutions',
    companyLogo: null,
    companyWebsite: 'https://bizcore.com',
    title: 'Accounting Clerk',
    jobType: 'Full-time',
    description: 'Maintain accounting records and assist senior accountants.',
    qualifications: ['Diploma in Accounting'],
    benefits: ['Career growth'],
    responsibilities: ['Record entries', 'Prepare simple reports'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 600,
    salaryMax: 800,
    applicationLink: 'https://bizcore.com/jobs/14',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '15',
    companyName: 'TrustBank',
    companyLogo: null,
    companyWebsite: 'https://trustbank.com',
    title: 'Finance Associate',
    jobType: 'Full-time',
    description:
      'Assist in preparing financial statements and monitoring cash flow.',
    qualifications: ['Bachelor’s in Finance'],
    benefits: ['Bonus'],
    responsibilities: ['Bank reconciliation', 'Prepare reports'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 950,
    salaryMax: 1150,
    applicationLink: 'https://trustbank.com/jobs/15',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '16',
    companyName: 'Unity Logistics',
    companyLogo: null,
    companyWebsite: 'https://unitylogistics.com',
    title: 'Inventory Accountant',
    jobType: 'Full-time',
    description: 'Maintain inventory records and valuation reports.',
    qualifications: ['Experience in logistics accounting'],
    benefits: ['Housing allowance'],
    responsibilities: ['Track inventory costs'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 850,
    salaryMax: 1100,
    applicationLink: 'https://unitylogistics.com/jobs/16',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '17',
    companyName: 'SkyTrade',
    companyLogo: null,
    companyWebsite: 'https://skytrade.com',
    title: 'Financial Controller',
    jobType: 'Full-time',
    description: 'Supervise all accounting operations and financial reporting.',
    qualifications: ['CPA', 'Leadership experience'],
    benefits: ['Company car', 'Bonus'],
    responsibilities: ['Lead accounting team', 'Oversee budget'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1500,
    salaryMax: 2000,
    applicationLink: 'https://skytrade.com/jobs/17',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '18',
    companyName: 'Capital Auditors',
    companyLogo: null,
    companyWebsite: 'https://capitalauditors.com',
    title: 'Internal Auditor',
    jobType: 'Full-time',
    description: 'Assess internal control systems and recommend improvements.',
    qualifications: ['Bachelor’s in Accounting', 'CIA preferred'],
    benefits: ['Training'],
    responsibilities: ['Conduct audits', 'Evaluate risks'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1000,
    salaryMax: 1300,
    applicationLink: 'https://capitalauditors.com/jobs/18',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '19',
    companyName: 'Ocean Finance',
    companyLogo: null,
    companyWebsite: 'https://oceanfinance.com',
    title: 'Accounting Supervisor',
    jobType: 'Full-time',
    description: 'Lead the accounting team and oversee month-end closings.',
    qualifications: ['5+ years experience', 'Bachelor’s in Accounting'],
    benefits: ['Bonus', 'Remote'],
    responsibilities: ['Supervise staff', 'Prepare reports'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1300,
    salaryMax: 1700,
    applicationLink: 'https://oceanfinance.com/jobs/19',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '20',
    companyName: 'Precision Books',
    companyLogo: null,
    companyWebsite: 'https://precisionbooks.com',
    title: 'Junior Auditor',
    jobType: 'Internship',
    description: 'Assist in audit fieldwork and report preparation.',
    qualifications: ['Accounting graduate', 'Analytical skills'],
    benefits: ['Training', 'Career path'],
    responsibilities: ['Assist audits', 'Verify documents'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 400,
    salaryMax: 600,
    applicationLink: 'https://precisionbooks.com/jobs/20',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  // ----------------- TEACHING JOBS (10) -----------------

  {
    id: '21',
    companyName: 'Global Academy',
    companyLogo: null,
    companyWebsite: 'https://globalacademy.com',
    title: 'Math Teacher',
    jobType: 'Full-time',
    description: 'Teach high school mathematics and prepare lesson plans.',
    qualifications: ["Bachelor's in Education", 'Math degree'],
    benefits: ['Health Insurance', 'Paid leave'],
    responsibilities: ['Deliver lessons', 'Grade assignments'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 700,
    salaryMax: 1000,
    applicationLink: 'https://globalacademy.com/jobs/21',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '22',
    companyName: 'Sunrise School',
    companyLogo: null,
    companyWebsite: 'https://sunriseschool.com',
    title: 'English Teacher',
    jobType: 'Full-time',
    description: 'Teach English language for grades 9–12.',
    qualifications: ["Bachelor's in English or Education"],
    benefits: ['Training programs'],
    responsibilities: ['Lesson planning', 'Assess student progress'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 600,
    salaryMax: 900,
    applicationLink: 'https://sunriseschool.com/jobs/22',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '23',
    companyName: 'Bright Minds Academy',
    companyLogo: null,
    companyWebsite: 'https://brightminds.com',
    title: 'Science Teacher',
    jobType: 'Full-time',
    description: 'Teach biology and chemistry with lab supervision.',
    qualifications: ["Bachelor's in Science Education"],
    benefits: ['Paid leave'],
    responsibilities: ['Conduct experiments', 'Prepare reports'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 650,
    salaryMax: 900,
    applicationLink: 'https://brightminds.com/jobs/23',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '24',
    companyName: 'Elite Academy',
    companyLogo: null,
    companyWebsite: 'https://eliteacademy.com',
    title: 'History Teacher',
    jobType: 'Full-time',
    description: 'Teach history curriculum for high school students.',
    qualifications: ["Bachelor's in History", 'Teaching certification'],
    benefits: ['Training', 'Health Insurance'],
    responsibilities: ['Create lesson plans', 'Evaluate students'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 600,
    salaryMax: 850,
    applicationLink: 'https://eliteacademy.com/jobs/24',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '25',
    companyName: 'Knowledge Hub',
    companyLogo: null,
    companyWebsite: 'https://knowledgehub.com',
    title: 'Physics Teacher',
    jobType: 'Full-time',
    description: 'Teach physics and supervise laboratory experiments.',
    qualifications: ["Bachelor's in Physics Education"],
    benefits: ['Paid leave', 'Training'],
    responsibilities: ['Plan lessons', 'Grade lab reports'],
    location: 'Bahir Dar',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 650,
    salaryMax: 900,
    applicationLink: 'https://knowledgehub.com/jobs/25',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '26',
    companyName: 'Bright Future School',
    companyLogo: null,
    companyWebsite: 'https://brightfuture.com',
    title: 'Chemistry Teacher',
    jobType: 'Full-time',
    description: 'Teach chemistry and lab safety procedures.',
    qualifications: ["Bachelor's in Chemistry Education"],
    benefits: ['Health Insurance'],
    responsibilities: ['Conduct experiments', 'Grade lab reports'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 650,
    salaryMax: 900,
    applicationLink: 'https://brightfuture.com/jobs/26',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '27',
    companyName: 'Global Learning Center',
    companyLogo: null,
    companyWebsite: 'https://globallearning.com',
    title: 'English Language Instructor',
    jobType: 'Full-time',
    description: 'Teach English to international students.',
    qualifications: ['TESOL certification', "Bachelor's in English"],
    benefits: ['Housing', 'Paid leave'],
    responsibilities: ['Prepare lessons', 'Assess proficiency'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 700,
    salaryMax: 1000,
    applicationLink: 'https://globallearning.com/jobs/27',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '28',
    companyName: 'Future Scholars Academy',
    companyLogo: null,
    companyWebsite: 'https://futurescholars.com',
    title: 'Mathematics Instructor',
    jobType: 'Full-time',
    description: 'Teach advanced mathematics to high school students.',
    qualifications: ["Bachelor's in Math Education"],
    benefits: ['Training', 'Health Insurance'],
    responsibilities: ['Lesson planning', 'Assess students'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 700,
    salaryMax: 950,
    applicationLink: 'https://futurescholars.com/jobs/28',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '29',
    companyName: 'Smart Academy',
    companyLogo: null,
    companyWebsite: 'https://smartacademy.com',
    title: 'Biology Teacher',
    jobType: 'Full-time',
    description: 'Teach biology curriculum and supervise labs.',
    qualifications: ["Bachelor's in Biology Education"],
    benefits: ['Training', 'Paid leave'],
    responsibilities: ['Conduct experiments', 'Grade students'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 650,
    salaryMax: 900,
    applicationLink: 'https://smartacademy.com/jobs/29',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '30',
    companyName: 'Excel Education',
    companyLogo: null,
    companyWebsite: 'https://exceled.com',
    title: 'Social Studies Teacher',
    jobType: 'Full-time',
    description: 'Teach social studies and history to secondary students.',
    qualifications: ["Bachelor's in Education"],
    benefits: ['Health Insurance'],
    responsibilities: ['Prepare lessons', 'Assess students'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 600,
    salaryMax: 850,
    applicationLink: 'https://exceled.com/jobs/30',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },

  // ----------------- MANAGEMENT JOBS (10) -----------------
  {
    id: '31',
    companyName: 'Global Corp',
    companyLogo: null,
    companyWebsite: 'https://globalcorp.com',
    title: 'Operations Manager',
    jobType: 'Full-time',
    description: 'Manage day-to-day operations and oversee team performance.',
    qualifications: [
      "Bachelor's in Business Administration",
      '3+ years experience',
    ],
    benefits: ['Health Insurance', 'Performance bonus'],
    responsibilities: ['Team management', 'Process optimization'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1500,
    salaryMax: 2000,
    applicationLink: 'https://globalcorp.com/jobs/31',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '32',
    companyName: 'Bright Ventures',
    companyLogo: null,
    companyWebsite: 'https://brightventures.com',
    title: 'Project Manager',
    jobType: 'Full-time',
    description: 'Lead projects from initiation to completion.',
    qualifications: ['PMP certification', '3+ years experience'],
    benefits: ['Bonus', 'Remote option'],
    responsibilities: ['Manage timelines', 'Coordinate teams'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1400,
    salaryMax: 1800,
    applicationLink: 'https://brightventures.com/jobs/32',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '33',
    companyName: 'Elite Management',
    companyLogo: null,
    companyWebsite: 'https://elitemanagement.com',
    title: 'General Manager',
    jobType: 'Full-time',
    description: 'Oversee overall operations and business strategy.',
    qualifications: ['MBA preferred', '5+ years experience'],
    benefits: ['Car allowance', 'Bonus'],
    responsibilities: ['Lead departments', 'Develop strategies'],
    location: 'Nairobi',
    country: 'Kenya',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 2000,
    salaryMax: 2500,
    applicationLink: 'https://elitemanagement.com/jobs/33',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '34',
    companyName: 'TechNova',
    companyLogo: null,
    companyWebsite: 'https://technova.com',
    title: 'Product Manager',
    jobType: 'Full-time',
    description: 'Define product roadmap and oversee execution.',
    qualifications: [
      'MBA or relevant degree',
      'Experience in software products',
    ],
    benefits: ['Remote work', 'Stock options'],
    responsibilities: ['Define roadmap', 'Coordinate teams'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1800,
    salaryMax: 2200,
    applicationLink: 'https://technova.com/jobs/34',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '35',
    companyName: 'Summit Holdings',
    companyLogo: null,
    companyWebsite: 'https://summitholdings.com',
    title: 'Operations Director',
    jobType: 'Full-time',
    description: 'Direct operations across multiple departments.',
    qualifications: ['MBA', '7+ years experience'],
    benefits: ['Bonus', 'Healthcare'],
    responsibilities: ['Strategic planning', 'Oversee operations'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 2200,
    salaryMax: 3000,
    applicationLink: 'https://summitholdings.com/jobs/35',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '36',
    companyName: 'NextGen Solutions',
    companyLogo: null,
    companyWebsite: 'https://nextgensolutions.com',
    title: 'HR Manager',
    jobType: 'Full-time',
    description: 'Manage recruitment, employee relations, and HR policies.',
    qualifications: ['Degree in HR or Business Administration'],
    benefits: ['Health Insurance', 'Training'],
    responsibilities: ['Manage HR team', 'Recruit staff'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1500,
    salaryMax: 1900,
    applicationLink: 'https://nextgensolutions.com/jobs/36',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '37',
    companyName: 'BizCore Management',
    companyLogo: null,
    companyWebsite: 'https://bizcore.com',
    title: 'Team Lead',
    jobType: 'Full-time',
    description: 'Lead a team of analysts and ensure project delivery.',
    qualifications: ['3+ years experience', 'Leadership skills'],
    benefits: ['Training', 'Bonus'],
    responsibilities: ['Lead team', 'Manage deliverables'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1300,
    salaryMax: 1700,
    applicationLink: 'https://bizcore.com/jobs/37',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '38',
    companyName: 'Global Logistics',
    companyLogo: null,
    companyWebsite: 'https://globallogistics.com',
    title: 'Supply Chain Manager',
    jobType: 'Full-time',
    description: 'Manage supply chain operations and optimize costs.',
    qualifications: ['MBA', 'Supply Chain experience'],
    benefits: ['Bonus', 'Healthcare'],
    responsibilities: ['Plan supply chain', 'Negotiate with suppliers'],
    location: 'Nairobi',
    country: 'Kenya',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1800,
    salaryMax: 2200,
    applicationLink: 'https://globallogistics.com/jobs/38',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '39',
    companyName: 'Alpha Enterprises',
    companyLogo: null,
    companyWebsite: 'https://alphaenterprises.com',
    title: 'Business Development Manager',
    jobType: 'Full-time',
    description: 'Lead business development and client acquisition strategies.',
    qualifications: ['MBA or Business degree', '3+ years experience'],
    benefits: ['Commission', 'Remote option'],
    responsibilities: ['Develop strategy', 'Lead sales team'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1600,
    salaryMax: 2000,
    applicationLink: 'https://alphaenterprises.com/jobs/39',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '40',
    companyName: 'Vision Corp',
    companyLogo: null,
    companyWebsite: 'https://visioncorp.com',
    title: 'Project Coordinator',
    jobType: 'Full-time',
    description: 'Coordinate projects across multiple departments.',
    qualifications: ['Business degree', 'Excellent communication skills'],
    benefits: ['Training', 'Bonus'],
    responsibilities: ['Coordinate tasks', 'Track progress'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1400,
    salaryMax: 1800,
    applicationLink: 'https://visioncorp.com/jobs/40',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },

  // ----------------- LAWYER JOBS (5) -----------------
  {
    id: '41',
    companyName: 'LexLaw Firm',
    companyLogo: null,
    companyWebsite: 'https://lexlaw.com',
    title: 'Corporate Lawyer',
    jobType: 'Full-time',
    description:
      'Provide legal advice to corporate clients on contracts and compliance.',
    qualifications: ['Law degree', 'Bar certification'],
    benefits: ['Healthcare', 'Bonus'],
    responsibilities: ['Draft contracts', 'Advise clients'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 2000,
    salaryMax: 2500,
    applicationLink: 'https://lexlaw.com/jobs/41',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '42',
    companyName: 'Justice Partners',
    companyLogo: null,
    companyWebsite: 'https://justicepartners.com',
    title: 'Litigation Lawyer',
    jobType: 'Full-time',
    description: 'Represent clients in civil and commercial disputes.',
    qualifications: ['Law degree', '3+ years experience'],
    benefits: ['Healthcare'],
    responsibilities: ['Prepare cases', 'Attend court hearings'],
    location: 'Nairobi',
    country: 'Kenya',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1800,
    salaryMax: 2200,
    applicationLink: 'https://justicepartners.com/jobs/42',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '43',
    companyName: 'LegalEase',
    companyLogo: null,
    companyWebsite: 'https://legalease.com',
    title: 'Tax Lawyer',
    jobType: 'Full-time',
    description: 'Advise clients on tax law and compliance issues.',
    qualifications: ['Law degree', 'Tax law specialization'],
    benefits: ['Training', 'Bonus'],
    responsibilities: ['Provide advice', 'Draft documents'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1900,
    salaryMax: 2300,
    applicationLink: 'https://legalease.com/jobs/43',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '44',
    companyName: 'Global Law Advocates',
    companyLogo: null,
    companyWebsite: 'https://globallaw.com',
    title: 'Legal Advisor',
    jobType: 'Full-time',
    description: 'Provide legal guidance to businesses and organizations.',
    qualifications: ['Law degree', '3+ years experience'],
    benefits: ['Bonus', 'Healthcare'],
    responsibilities: ['Draft policies', 'Advise management'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1800,
    salaryMax: 2200,
    applicationLink: 'https://globallaw.com/jobs/44',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '45',
    companyName: 'Justice Advocates',
    companyLogo: null,
    companyWebsite: 'https://justiceadvocates.com',
    title: 'Legal Consultant',
    jobType: 'Contract',
    description: 'Advise companies on compliance and corporate law matters.',
    qualifications: ['Law degree', '3+ years experience'],
    benefits: ['Remote work', 'Flexible hours'],
    responsibilities: ['Advise clients', 'Draft agreements'],
    location: 'Remote',
    country: 'Global',
    hourlyRate: 50,
    fixedBudget: null,
    salaryMin: null,
    salaryMax: null,
    applicationLink: 'https://justiceadvocates.com/jobs/45',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },

  // ----------------- RESEARCH JOBS (5) -----------------

  {
    id: '46',
    companyName: 'Ethiopia Research Institute',
    companyLogo: null,
    companyWebsite: 'https://eri.org',
    title: 'Research Analyst',
    jobType: 'Full-time',
    description:
      'Conduct research on economic and social development projects.',
    qualifications: ["Bachelor's in Economics or related field"],
    benefits: ['Health Insurance'],
    responsibilities: ['Collect data', 'Prepare reports'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1000,
    salaryMax: 1300,
    applicationLink: 'https://eri.org/jobs/46',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '47',
    companyName: 'Global Research Labs',
    companyLogo: null,
    companyWebsite: 'https://grlabs.com',
    title: 'Data Researcher',
    jobType: 'Full-time',
    description:
      'Perform quantitative and qualitative research for various industries.',
    qualifications: ["Bachelor's degree", 'Experience with surveys'],
    benefits: ['Training', 'Remote option'],
    responsibilities: ['Data collection', 'Analyze results'],
    location: 'Remote',
    country: 'Global',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1200,
    salaryMax: 1500,
    applicationLink: 'https://grlabs.com/jobs/47',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '48',
    companyName: 'Innovation Research Hub',
    companyLogo: null,
    companyWebsite: 'https://irhub.com',
    title: 'Junior Researcher',
    jobType: 'Full-time',
    description: 'Assist senior researchers in data collection and analysis.',
    qualifications: ["Bachelor's degree", 'Analytical skills'],
    benefits: ['Training'],
    responsibilities: ['Assist research projects', 'Data entry'],
    location: 'Addis Ababa',
    country: 'Ethiopia',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 800,
    salaryMax: 1000,
    applicationLink: 'https://irhub.com/jobs/48',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '49',
    companyName: 'Tech Research Solutions',
    companyLogo: null,
    companyWebsite: 'https://techresearch.com',
    title: 'Research Scientist',
    jobType: 'Full-time',
    description: 'Conduct applied research in technology and innovation.',
    qualifications: ['Master’s or PhD in relevant field'],
    benefits: ['Healthcare', 'Bonus'],
    responsibilities: ['Design experiments', 'Analyze results'],
    location: 'Nairobi',
    country: 'Kenya',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1800,
    salaryMax: 2200,
    applicationLink: 'https://techresearch.com/jobs/49',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
  {
    id: '50',
    companyName: 'Global Policy Research',
    companyLogo: null,
    companyWebsite: 'https://globalpolicyresearch.com',
    title: 'Policy Researcher',
    jobType: 'Full-time',
    description:
      'Research and analyze policies to provide actionable insights.',
    qualifications: ["Bachelor's in Political Science or Economics"],
    benefits: ['Remote', 'Training'],
    responsibilities: ['Policy analysis', 'Report preparation'],
    location: 'Remote',
    country: 'Global',
    hourlyRate: null,
    fixedBudget: null,
    salaryMin: 1500,
    salaryMax: 1800,
    applicationLink: 'https://globalpolicyresearch.com/jobs/50',
    postedAt: new Date(),
    status: 'Open',
    workType: 'Onsite',
  },
];
